import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import "./globals.css";

const dmmono = DM_Mono({
  weight: ["300", "400", "500"],
  variable: "--font-dm-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: {
    title: "Mnexia",
  },
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmmono.variable} antialiased`}>{children}</body>
    </html>
  );
}
